# Hyprland Window Manager Configuration
#
# Keybindings Overview:
#   Super + Q       = Terminal
#   Super + F       = Browser
#   Super + E       = File Manager
#   Super + R       = App Menu
#   Super + C       = Close Window
#   Super + L       = Lock Screen
#   Super + M       = Power Menu
#   Super + J       = Toggle Split
#   Super + V       = Toggle Floating
#   Super + P       = Pseudo Tiling
#   Super + S       = Scratchpad
#   Super + arrows  = Navigate Windows
#   Super + Shift + arrows = Move Windows
#   Super + Alt + arrows   = Resize Windows
#   Super + 1-9     = Switch Workspaces
#   Super + Shift + 1-9    = Move Window to Workspace
#   Super + Alt + 1-9      = Move Window to Workspace Silent
#   Alt + Return    = Fullscreen

{ self, inputs, ... }:
{
  flake.nixosModules.modulesDesktopHyprHyprland =
    {
      config,
      lib,
      pkgs,
      ...
    }:
    let
      username = config.userOptions.username;
      browser = config.userOptions.browser;
      grim = lib.getExe pkgs.grim;
      slurp = lib.getExe pkgs.slurp;
      wlCopy = "${pkgs.wl-clipboard}/bin/wl-copy";
      wlPaste = "${pkgs.wl-clipboard}/bin/wl-paste";
      swappy = lib.getExe pkgs.swappy;
      zbar = lib.getExe pkgs.zbar;
      notifySend = "${pkgs.libnotify}/bin/notify-send";
    in
    {
      imports = [
        inputs.home-manager.nixosModules.home-manager
      ];

      home-manager.users.${username} = _: {
        wayland.windowManager.hyprland = {
          enable = true;
          xwayland.enable = true;
          portalPackage = pkgs.xdg-desktop-portal-hyprland;

          # UWSM handles systemd integration — disabling Hyprland's own to avoid conflict
          systemd = {
            enable = false;
            enableXdgAutostart = false;
            variables = [ ];
          };

          # Pass settings as generated Lua configuration into Hyprland
          extraConfig = ''
            -- Hyprland Window Manager Configuration (~/.config/hypr/hyprland.conf)
            --
            -- Keybindings Overview:
            --   Super + Q       = Terminal
            --   Super + F       = Browser
            --   Super + E       = File Manager
            --   Super + R       = App Menu
            --   Super + C       = Close Window
            --   Super + L       = Lock Screen
            --   Super + M       = Power Menu
            --   Super + J       = Toggle Split
            --   Super + V       = Toggle Floating
            --   Super + P       = Pseudo Tiling
            --   Super + S       = Scratchpad
            --   Super + arrows  = Navigate Windows
            --   Super + Shift + arrows = Move Windows
            --   Super + Alt + arrows   = Resize Windows
            --   Super + 1-9     = Switch Workspaces
            --   Super + Shift + 1-9    = Move Window to Workspace
            --   Super + Alt + 1-9      = Move Window to Workspace Silent
            --   Alt + Return    = Fullscreen

            -- Variables
            -- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

            local mainMod = "Super"
            local browser = "xdg-open http://" -- Change to your default browser (e.g., firefox, zen)

            -- Ecosystem

            hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
            hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
            hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
            hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
            hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })
            hl.animation({
                leaf = "windows",
                enabled = true,
                speed = 4.79,
                bezier = "easeOutQuint",
            })
            hl.animation({
                leaf = "windowsIn",
                enabled = true,
                speed = 4.1,
                bezier = "easeOutQuint",
                style = "popin 87%",
            })
            hl.animation({
                leaf = "windowsOut",
                enabled = true,
                speed = 1.49,
                bezier = "linear",
                style = "popin 87%",
            })
            hl.animation({
                leaf = "border",
                enabled = true,
                speed = 5.39,
                bezier = "easeOutQuint",
            })
            hl.animation({
                leaf = "fade",
                enabled = true,
                speed = 3.03,
                bezier = "quick",
            })
            hl.animation({
                leaf = "fadeIn",
                enabled = true,
                speed = 1.73,
                bezier = "almostLinear",
            })
            hl.animation({
                leaf = "fadeOut",
                enabled = true,
                speed = 1.46,
                bezier = "almostLinear",
            })
            hl.animation({
                leaf = "layers",
                enabled = true,
                speed = 3.81,
                bezier = "easeOutQuint",
            })
            hl.animation({
                leaf = "layersIn",
                enabled = true,
                speed = 4,
                bezier = "easeOutQuint",
                style = "fade",
            })
            hl.animation({
                leaf = "layersOut",
                enabled = true,
                speed = 1.5,
                bezier = "linear",
                style = "fade",
            })
            hl.animation({
                leaf = "workspaces",
                enabled = true,
                speed = 1.94,
                bezier = "almostLinear",
                style = "fade",
            })
            hl.animation({
                leaf = "workspacesIn",
                enabled = true,
                speed = 1.21,
                bezier = "almostLinear",
                style = "fade",
            })
            hl.animation({
                leaf = "workspacesOut",
                enabled = true,
                speed = 1.94,
                bezier = "almostLinear",
                style = "fade",
            })

            hl.bind(mainMod .. " + C", hl.dsp.window.close())
            hl.bind(mainMod .. " + M", hl.dsp.exit())
            hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
            hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("hyprlock"))
            hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("dunstctl history-pop"))
            hl.bind("ALT + Return", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))

            hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd("kitty"))
            hl.bind(mainMod .. " + F", hl.dsp.exec_cmd(browser))
            hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("uwsm app -- dolphin"))
            hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("vicinae toggle"))

            hl.bind("Print", hl.dsp.exec_cmd("grim - | wl-copy"))
            hl.bind(mainMod .. " + SHIFT + Print", hl.dsp.exec_cmd("grim -g \"$(slurp -w 0)\" - | wl-copy"))
            hl.bind(mainMod .. " + CTRL + S", hl.dsp.exec_cmd("grim -l 0 - | wl-copy"))
            hl.bind(mainMod .. " + CTRL + SHIFT + S", hl.dsp.exec_cmd("grim -l 0 - | wl-copy"))
            hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd("wl-paste | swappy -f -"))
            hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.exec_cmd("result=$(grim -g \"$(slurp -w 0)\" - | zbar -q --raw - 2>/dev/null) && echo \"$result\" | wl-copy && notify-send \"QR Code\" \"$result\" || notify-send \"QR Scan\" \"No QR code found\""))

            hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
            hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))
            hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
            hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))

            hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
            hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
            hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
            hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

            hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.move({ direction = "l" }))
            hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.move({ direction = "d" }))
            hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.move({ direction = "u" }))
            hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.move({ direction = "r" }))

            hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.move({ direction = "l" }))
            hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "r" }))
            hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.move({ direction = "u" }))
            hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.move({ direction = "d" }))

            hl.bind(mainMod .. " + ALT + left", hl.dsp.window.resize({ x = -40, y = 0, relative = true }))
            hl.bind(mainMod .. " + ALT + right", hl.dsp.window.resize({ x = 40, y = 0, relative = true }))
            hl.bind(mainMod .. " + ALT + up", hl.dsp.window.resize({ x = 0, y = -40, relative = true }))
            hl.bind(mainMod .. " + ALT + down", hl.dsp.window.resize({ x = 0, y = 40, relative = true }))

            hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
            hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
            hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
            hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
            hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
            hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
            hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
            hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
            hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
            hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

            hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
            hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
            hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
            hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
            hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
            hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
            hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
            hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
            hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
            hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

            hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
            hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

            hl.bind(mainMod .. " + ALT + 1", hl.dsp.window.move({ workspace = 1, follow = false }))
            hl.bind(mainMod .. " + ALT + 2", hl.dsp.window.move({ workspace = 2, follow = false }))
            hl.bind(mainMod .. " + ALT + 3", hl.dsp.window.move({ workspace = 3, follow = false }))
            hl.bind(mainMod .. " + ALT + 4", hl.dsp.window.move({ workspace = 4, follow = false }))
            hl.bind(mainMod .. " + ALT + 5", hl.dsp.window.move({ workspace = 5, follow = false }))
            hl.bind(mainMod .. " + ALT + 6", hl.dsp.window.move({ workspace = 6, follow = false }))
            hl.bind(mainMod .. " + ALT + 7", hl.dsp.window.move({ workspace = 7, follow = false }))
            hl.bind(mainMod .. " + ALT + 8", hl.dsp.window.move({ workspace = 8, follow = false }))
            hl.bind(mainMod .. " + ALT + 9", hl.dsp.window.move({ workspace = 9, follow = false }))
            hl.bind(mainMod .. " + ALT + 0", hl.dsp.window.move({ workspace = 10, follow = false }))

            hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
            hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

            hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
            hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
            hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
            hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
            hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 10%+"), { locked = true, repeating = true })
            hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 10%-"), { locked = true, repeating = true })

            hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
            hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
            hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

            hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
            hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())
            hl.config({
                ecosystem = {
                    no_update_news = true,
                },
                -- Input
                input = {
                    kb_layout = "us",
                    follow_mouse = 1,
                    sensitivity = 0,
                    numlock_by_default = true,
                    touchpad = {
                        natural_scroll = false,
                    },
                },
                -- General Layout
                general = {
                    gaps_in = 0,
                    gaps_out = 0,
                    border_size = 0,
                    resize_on_border = false,
                    allow_tearing = false,
                    layout = "dwindle",
                },
                -- Misc Options
                misc = {
                    disable_hyprland_logo = true,
                },
                -- Decoration
                decoration = {
                    rounding = 10,
                    rounding_power = 2,
                    active_opacity = 1.0,
                    inactive_opacity = 1.0,
                    blur = {
                        enabled = true,
                        size = 3,
                        passes = 1,
                        vibrancy = 0.1696,
                    },
                    shadow = {
                        enabled = true,
                        range = 4,
                        render_power = 3,
                    },
                },
                -- Animations
                animations = {
                    enabled = true,
                },
                -- Layout-Specific Config
                dwindle = {
                    preserve_split = true,
                    split_width_multiplier = 1.35,
                },
                master = {
                    new_status = "master",
                },
                -- Startup Executions
                -- Keybindings
                -- ── System ─────────────────────────
                -- ── Applications ───────────────────
                -- ── Screenshot ─────────────────────
                -- ── Focus: vim-style ───────────────
                -- ── Focus: arrow keys ──────────────
                -- ── Move window: vim-style ─────────
                -- ── Move window: arrow keys ────────
                -- ── Resize window ──────────────────
                -- ── Workspace switching ────────────
                -- ── Move window to workspace ───────
                -- ── Scratchpad ─────────────────────
                -- ── Move window to workspace silent ──
                -- ── Scroll workspaces ──────────────
                -- ── Media & System Controls ────────
                -- ── Mouse Binds ────────────────────
            })

            hl.on("hyprland.start", function()
                hl.exec_cmd("vicinae server")
            end)


          '';
        };
      };
    };
}